### ISSUE TITLE
Xcode 7 compatiblity

### ISSUE THREAD

**Issue by chsculpt** [MaheshRS/symbolication-plugin#1]

**Comment by MaheshRS** [comment]
Fixed in commit `a8a6d14bb847fc46b6fc79842301c5ec2b10dbf7`. Thanks :octocat:

**Comment by chsculpt** [comment]
It didn’t work for me the first time I had tried it.   I saw the plugin built in the Plugins folder but it didn’t load in Xcode.   I deleted the plugin and rebuilt it, now it loads just fine.   Thank you this tool is a great help!

Carl

**Comment by MaheshRS** [comment]
@chsculpt Glad to hear the tool is helping. Thanks again!
