### ISSUE TITLE
Xcode version bump

### ISSUE THREAD

**Issue by Cyclic** [MaheshRS/symbolication-plugin#2]
I wasn't able to get the plugin to load until I added the following UUID to the Info.plist file inside of the Symbolicate Xcode project, and then running it. To get the UUID, I used the following:
defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID {UUID}                                                                   ⏎
7265231C-39B4-402C-89E1-16167C4CC990

The above is Xcode 7.

**Comment by MaheshRS** [comment]
@Cyclic updated DVTPlugInCompatibilityUUIDs to support Xcode 7 in commit `79bb663fc29be24e3b66976cdd6a3e5500d28bcb`. Thanks for mentioning the issue :octocat:
